# Site settings
title: Icaro Ramires - Front End Developer
description: "Desenvolvimento web, linux e outras coisitas"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://icaroramiires.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'
# User settings
username: icaroramiires
user_title: Icaro Ramires - FrontEnd
email: icarobsi@hotmail.com
twitter_username: _icaroramiires
github_username:  icaroramiires
gplus_username:  loremipsum
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: MOBY - Intel® Embedded Systems Competition 2016 - SBESC
    url: https://github.com/allexandresampaio/wservice.moby
  - name: FOXPARKING - Hackathon IoT Telefônica Vivo 2014 - CAMPUS PARTY
    url: https://github.com/icaroramiires/Webapp_estacionamento
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
